### ISSUE TITLE
Some questions about Hifiasm 0.15 (r327)

### ISSUE THREAD

**Issue by StevenBai97** [chhylp123/hifiasm#103]
Hello!
I have used the new version to assemble the genome (Estimated size: 474 Mb, heterozygosity: 1.27%, duplication: 53%) with HiC mode. Commands to run Hifiasm are "hifiasm -l 3 -o hifiasm -t 30 HiFi.fasta --h1 HiC_R1_clean.rd.fq.gz --h2 HiC_R2_clean.rd.fq.gz". The result is wonderful (BUSCO: 99.0%, N50: 3.87Mb), but I have some questions about the output of Hifiasm 0.15 (r327).
(1) The assembled genome is about 555Mb (a bit larger than estimated size), and the BUSCO is C:99.0%[S:95.4%,D:3.6%], F:0.5%, M:0.5%. There seems to be some redundancy in the genome. Whether some parameters need adjustment (such as "-s 0.45" ) to reduce the duplication or the result needs purging with other software?
(2) I used Hifiasm 0.142 to assemble the same genome several days ago. Commands are "hifiasm -l 3 -o hifiasm -t 30 HiFi.fasta". The BUSCO of previous result is C:98.7%[S:97.7%,D:1.0%], and N50 is 5.4Mb, as well as  the genome size with 518 Mb. I'm not sure which result is more accuracy. Hifiasm 0.15 (r327) with HiC mode or Hifiasm 0.142 ?
(3) In output, the haplotype is smaller than primary assembly. What is the difference between the primary assembly and the balanced haplotypes? 
I'm looking forward to your reply. Thanks a lot.

**Comment by lh3** [comment]
What is the size of the primary assembly and of the two phased haplotypes?

**Comment by StevenBai97** [comment]
> What is the size of the primary assembly and of the two phased haplotypes?

The size of primary assembly is 555Mb, and the two phased haplotypes are 531Mb and 525Mb, respectively.

**Comment by chhylp123** [comment]
In theory, primary assembly should be larger than each of two phased haplotypes, since it keeps the unique parts in both haplotypes. For example, primary assembly of HG002 should consist of both chrX and chrY, while phased haplotype only keep one of them. However, the procedure of purging is messy, it is hard to say. I personally think new version should be better. At least for human, the new assembly keeps more segdups. 

>Whether some parameters need adjustment (such as "-s 0.45" ) to reduce the duplication or the result needs purging with other software?

Increasing '--purge-cov' will make purging and phasing more aggressive, which should be larger than hom peak. I personally think it is no need to run other tools, since they may collapse segdups. 

>Hifiasm 0.15 (r327) with HiC mode or Hifiasm 0.14.2 

If you really want to get Hifiasm 0.14.2 assembly with 0.15, you can use '--n-hap 3' and '--primary'. In this case, hifiasm has no diploid assumption.
