### ISSUE TITLE
question about N50

### ISSUE THREAD

**Issue by ptrebert** [chhylp123/hifiasm#134]
Hi,
this is a question specifically for Heng; Heng, I recall that you mentioned during one of the HPRC calls that you observed a tendency for lower contig N50s in assemblies of African samples. Back then, the cause for this was still elusive (that was month ago...).
Now, we still see a comparatively low N50 for African samples every now and then (with v0.15.2). Could this still be an effect of hifiasm (I saw only a generic statement about improved N50s in the release notes for v0.14), or is that rather unlikely? I am just double-checking here because, so far, we couldn't find any data-related explanation for this observation. Any insight you can provide would be much appreciated, thanks a lot!
Best,
Peter

**Comment by lh3** [comment]
Sorry for missing your question. I tend to believe the varying N50 is primarily caused by raw data quality and the varying N50 between populations is a batch effect: samples sequenced at one time frame by a particular sequencing center tend to have lower quality. Note that more recent samples also have lower quality.

I don't know what is the exact cause. The short N50 is not strongly associated with read coverage or read length.

**Comment by ptrebert** [comment]
Thanks a lot for the detailed answer. Robustly identifying batch effects is always a challenge given the low number of samples per batch in my data set, but it wouldn't surprise me anymore...

> Note that more recent samples also have lower quality.

Interesting; you happen to know if that is likely resulting from a change in a wet lab protocol?

**Comment by lh3** [comment]
I heard the chemistry shipped from PacBio had some problems.

**Comment by ptrebert** [comment]
Ok, thanks for sharing your insights.
