### ISSUE TITLE
Inverted contigs

### ISSUE THREAD

**Issue by ardy20** [chhylp123/hifiasm#181]
Dear Sir

We dot plotted two plant assemblies one HiC scaffolded (species 1) and the second species HiFiasm assembled. The results is very promising with large scaffolds but some of the chromosome level contigs (the entire contig) look inverted (inversion).

Has anyone faced such a problem? Please check the attached Figure out.

![HicSpc1vsHiFiasmSpc2](https://user-images.githubusercontent.com/63028911/132296232-ab34cfe5-9b94-4541-b9b6-09a791e3685b.PNG)

**Comment by scottgeib** [comment]
the orientation of the chromosome is going to be arbitrary if the contig is chromosome length.  If the contig inversion is relative to a related genome, then you would just want to invert the contig prior to mapping if you did not allow for re-orientation during construction of dot plot.  If you want to validate the chromosomes using HiC data from the same species, you could map the HiC data to the HiFi assembly to confirm the correctness of the contigs as well as edit their orientation and order relative to each other using tools such as Juicebox assembly toolkit.  Contig 000007I looks like it is not supported based off of alignment to the other genome (showing as two chromosomes there), but that could be fine if not same species and there has been chromosome evolution between the species. Inversions at the telomere relative to a HiC assembly can at times be from incorrect orientation during HiC assembly rather than a HiFiASM error in my experience.  How much you trust the HiC assembly is a lot dependent on the assembly that it is based on.   If this is macadamia , i think haploid chromosome number is 14 chromosomes based on linkage mapping.

**Comment by HenrivdGeest** [comment]
Since it looks you  plot your images with dgenies, just right click on a inverted piece and click invert. Like @scottgeib, its just arbitrary.

**Comment by ardy20** [comment]
Thanks for suggestions and explanations. I will try all of the recommendations.
