### ISSUE TITLE
Using subreads

### ISSUE THREAD

**Issue by kkrizanovic** [chhylp123/hifiasm#201]
hello,

I'm trying to assemble a plant genome of roughly 4Gbp with 11 chromosomes. ATM I'm working on haploid assembly, however the genome is diploid.

I've got about 25X of hifi reads, and a bunch of subreads as well.

I've got about 3000 contigs using hifi reads only. I was wandering is there any point in trying to use subreads for the assembly as well? If so, how would i go about it?

**Comment by fengli-eGen** [comment]
Following up this thread. I wonder if hifiasm can assemble reads from reads.bam in pacbio ccs pipeline. Reads.bam contains reads that did't pass HiFi standards (min-passes >=3, min quality >20). I'm performing a de novo genome assembly, and my data is not good using using HiFi standards since it discarded too many reads so that I lack coverage. So I wonder if reads.bam --> reads.fasta --> hifiasm works.

FYI, I attach what ccs reads.bam is:
https://ccs.how/faq/reads-bam 
What is in the reads.bam?
HiFi Reads with predicted accuracy ≥Q20 (rq ≥ 0.99)
Lower-quality but still polished consensus reads with predicted accuracy <Q20 (rq < 0.99)
Unpolished consensus reads (rq = -1)
Partial or single full-length subreads unaltered (rq = -1)

Thanks!
Feng

**Comment by chhylp123** [comment]
You can have a try. I'm also curious about the results. In theory, it should work.

**Comment by fengli-eGen** [comment]
My genome size is ~2.9Gbp and have ~180X using ccs reads.bam. I have 4 ccs reads.bam which I converted to fastq files, each ~250G big. To test hifiasm, I subsampled one of the SMRT cells and only used 10% of the data for testing (10% of 
[wt_ccs_reads.log](https://github.com/chhylp123/hifiasm/files/8256633/wt_ccs_reads.log)
my one SMRT cell is ~25 G big).

```
seqtk sample -s100 /data2/ccs/wt_1A01_reads.bam.fastq.gz 0.1 > sub1.fq
hifiasm -o  wt_ccs_reads.asm  -t 50 -f38 sub1.fq 1> wt_ccs.stdout 2> wt_ccs_reads.log
```

It di
[wt_ccs_reads.log](https://github.com/chhylp123/hifiasm/files/8256645/wt_ccs_reads.log)
d completed. But I do observe so-called weird kmer histogram. See attached. So I wonder if this means I cannot use ccs reads.bam which contains things other than real HiFi data for hifiasm pipeline? Or even though it had a weird histogram, hifiasm can still generate an assembly if I use all my data (170X coverage with 4 fastq file, 250G per file)? 

Thanks!

**Comment by lh3** [comment]
> Or even though it had a weird histogram, hifiasm can still generate an assembly from this ccs reads.bam if I use all my data

Please learn to evaluate an assembly by yourself. Without looking at the assembly statistics, we don't know whether it is ok or not.
