### ISSUE TITLE
Much larger genome size in inbred species with parameter '-l0'

### ISSUE THREAD

**Issue by Axolotl233** [chhylp123/hifiasm#211]
Hi community,

Recently i assemblied a genome of selfing diploid species using hifiasm with recommended parameters ‘-l0’. I found the final genome size is much larger than our suvery. the contig length were surveyed and show unusual situation: the sum of longest 12 contig coincide with expected genome size. Other contigs (more than 10000) were one order of magnitude shorter than these 12 contigs, and occupied more than 60% of total genome assembly. i checked log and found  heterozygous and homozygous peaks were -1 and 72, thats seemly correct.

i also run hifiasm with defalut parameter, and not get properly result, there still show larger genome sizes and many short contig gulted the assembly. could you give me some adivce for this plight?

the log file of '-l0' has been uploaded in appendix, and the log of default parameter is lost...
[asm.log](https://github.com/chhylp123/hifiasm/files/7567490/asm.log)
[Bsta.bp.p_ctg.fa.len.txt](https://github.com/chhylp123/hifiasm/files/7567491/Bsta.bp.p_ctg.fa.len.txt)

**Comment by lh3** [comment]
Based on the k-mer profile, part of your data appears to have very low quality. This will affect assembly in unexpected ways.

**Comment by Axolotl233** [comment]
@lh3 thanks Heng for quick reply. 
whether low quality of reads indicated by too much of low depth (peak nearby 0)？and the ccs reads were called by company, how i filter it mannually?

**Comment by Axolotl233** [comment]
Hi there, 

I counted the reads mapping rate and region coverage using short reads, the result shows high rates mapping rate (~99% raw and ~98% properly paired) but in contrast, the region coverage only is 37%,  many of short contigs not have any alignment.

i think there maybe have DNA contamination, is there have any parameter could filter these contig?

**Comment by lh3** [comment]
You can calculate the expected number of errors per read, assuming your base quality is accurate. The default PacBio CCS pipeline discards reads Q20 or lower. You can confirm with the sequencing vendor or write your script to check whether this filter has been applied. If your reads are already Q20+, the huge peak at k-mer count 2 is likely to be caused by contamination. You may check contig read coverage or use a close species to filter, but anyway, the assembly quality will be reduced.

> is there have any parameter could filter these contig?

No. Hifiasm is designed for data without contamination. Actually, I don't think there are robust ways to filter contaminations.

**Comment by Axolotl233** [comment]
@lh3 
thanks heng for advices , You can temporarily close this question.
