### ISSUE TITLE
Information about het variants in read set

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#230]
Hello Haoyu,

Hifiasm finds out heterozygous variants during error correction, and does error correction based on that as suggested in the paper. Is it possible to make this module print out information in the output log or a separate file, e.g., read ids, count of het alleles in each read, haplotype id (if available) etc.

Thanks!
Chirag

<img width="537" alt="Screenshot 2022-01-12 at 1 56 04 PM" src="https://user-images.githubusercontent.com/15384057/149090967-fa6e1837-83eb-434c-ad8a-5bb16ae22789.png">

**Comment by chhylp123** [comment]
I can do that. So what exactly information do you need? Do you just need the count of het alleles in each read?

**Comment by cjain7** [comment]
>Do you just need the count of het alleles in each read?
Yes that would be good. Thank you. Would this include the complete set of reads (including contained reads)?

**Comment by cjain7** [comment]
Haoyu, please let me know if this looks do-able this week. Alternatively, if you can point me to the appropriate function(s), I could also edit the code. Thanks!

**Comment by chhylp123** [comment]
Sorry for the delay. I will push the code to github today.

**Comment by chhylp123** [comment]
@cjain7 I have added the option `--dbg-het-cnt` at this branch (https://github.com/chhylp123/hifiasm/tree/hifiasm_dev_debug). The count of het alleles in each read will be printed to the `*het_cnt.log`. Please note these are the number of informative sites in each read, instead of het alleles alone. Variants between different copies of repeats might be also identified as informative sites.

**Comment by cjain7** [comment]
Really appreciate your help! I'm able to use the code and obtain `*het_cnt.log` file.
