### ISSUE TITLE
Is racon necessary for the hifiasm downstream？

### ISSUE THREAD

**Issue by baozg** [chhylp123/hifiasm#28]
Hi, @chhylp123 

Since the `hifiasm` have 3 rounds correct for HiFi reads，the quality of default assembly from hifiasm is high enough. Do I need to mapping the HiFi fastq to the assembly to do polishing using racon?

Thanks.

Zhigui Bao

**Comment by lh3** [comment]
Racon is likely to give you worse consensus.

**Comment by baozg** [comment]
So the hifiasm assembly is ready to scaffold (by HiC, BioNano etc), it don't need any polishing step?

**Comment by chhylp123** [comment]
Worse consensus is the common problem of all polishing tools, instead of Racon. For now most polishing tools are designed for CLR reads and based on read alignment. The read alignment might be confused by very low heterozygous rate and segdups difference, so polishing tools may collapse heterozygous variants/segdups. I personally recommend not to perform polishing step unless you can make Racon haplotype-aware.
