### ISSUE TITLE
Any recommended parameter-set to adjust  the low coverage hifi data(15~20X)

### ISSUE THREAD

**Issue by KaiqiangLiu** [chhylp123/hifiasm#7]
Hi,
Thanks for developing this cool tool.
Any recommended parameter-set to adjust for the large genome assembly with low coverage hifi data(15~20X)? like -k ？

Thanks!

**Comment by jelber2** [comment]
You might have to simulate HiFi coverage. For example get a similar haploid genome assembly to what you have not yet assembled, then mutate it into diploid (or whatever your ploidy is) with `mutate.sh` from BBTools/BBMap (https://sourceforge.net/projects/bbmap/files/) with some predicted "heterozygosity rate". Then simulate random reads with `randomreads.sh` (also from BBTools/BBMap) using PacBio HiFi characteristics (12-15Kbp, error rate 1.0-1.5% or whatever you desire) such as the example commands below. Note that I put coverage=10 because there are actually two haplotypes produced by `mutate.sh` when `ploidy=2`, so that 10x diploid coverage equals 20x haploid coverage.

    mutate.sh in=curated.fasta ploidy=2 maxindel=5 subrate=0.0002 hetrate=0.05 indelrate=0.00002 out=curated.fasta.diploid.mut.fasta vcf=curated.fasta.diploid.mut.vcf.gz 2>mutate.log &
    randomreads.sh ref=curated.fasta illuminanames=t coverage=10 gaussianlength=t pacbio=t pbmin=0.01 pbmax=0.015 out=random_reads_ccs.fasta minlength=10000 midlength=12000 maxlength=15000 > random_reads_ccs.log 2>&1

Then use QUAST-LG (https://github.com/ablab/quast) to compare you hifiasm results on different values of `k`,`r`, and `a` with curated.fasta.diploid.mut.fasta if you use unitigs or curated.fasta if you use primary contigs (just a suggestion).

**Comment by chhylp123** [comment]
I agree with @jelber2

**Comment by KaiqiangLiu** [comment]
Thanks for your @jelber2  useful suggestion with all the details. 
Thanks for your @chhylp123  reply.
