### ISSUE TITLE
Purge again or polish?

### ISSUE THREAD

**Issue by StevenBai97** [chhylp123/hifiasm#83]
Hi, haoyu
I’m a beginner in bioinformatics and recently de novo assemble a genome with high heterozygosity (1.27%) and high duplication (53%). The sequencing depth is around 45x. I used hifiasm v0.14 to assemble and achieved the result file “*.p_ctg.fa”. Command is “hifiasm -o hifiasm --high-het -t 30 input.fa”. I meet some problems and want your advice.
(1)The N50 of assembled contigs is about 3.4Mb. Should I change the parameter (such as add “-l 2”) or use purge_dups to purge again to improve the quality of assembly?
(2) I have the short reads of this species from Illumina Hiseq platform. Is it necessary to polish the contigs from hifiasm with the short reads?
I'll really appreciate your suggestions.
Thanks.

**Comment by chhylp123** [comment]
(1) What's the estimated haploid genome size of your samples? If current “*.p_ctg.fa” has similar size as the estimated haploid genome size, it should be OK. Otherwise you'd better to use purge_dups to purge on (“*.p_ctg.fa” + “*.a_ctg.fa”). Current hifiasm has an issue that it may not be able to do enough purge for samples with high heterozygosity. We have already fixed this problem in the new version and will release it soon.
(2) Usually no need to polish with short reads. The reason is that short reads mapping is more likely to be wrong so that it would introduce errors by wrong alignment.

**Comment by StevenBai97** [comment]
> (1) What's the estimated haploid genome size of your samples? If current “_.p_ctg.fa” has similar size as the estimated haploid genome size, it should be OK. Otherwise you'd better to use purge_dups to purge on (“_.p_ctg.fa” + “*.a_ctg.fa”). Current hifiasm has an issue that it may not be able to do enough purge for samples with high heterozygosity. We have already fixed this problem in the new version and will release it soon.
> (2) Usually no need to polish with short reads. The reason is that short read mapping is more likely to be wrong so that it would introduce errors by wrong alignment.

Thanks for your reply.
The estimated genome size is about 474 Mb based on k-mer analysis, but the assembled genome is about 560 Mb. I wonder if my way to estimated genome size is somewhat wrong, because the complete BUSCOs of assembled genome is 98.6% [S:96.6%,D:2.0%] and the N50 is 3.4 Mb. I think the assembly result is very good. I'm going to use purge_dups to purge ".p_ctg.fa", and looking forward to a better result.
Hifiasm is a very good software, and we shall be looking forward to a better version.

**Comment by lh3** [comment]
GenomeScope only gives you a crude estimate. That estimate is often too small. Purge_dups sometimes helps but more often makes the assembly worse.

**Comment by StevenBai97** [comment]
After purging, the N50 of " .p_ctg.fa" was increased to 4.1Mb, but the complete BUSCOs was improved inapparently (from 98.3% [S:96.0%,D:2.3%] to 98.7% [S:97.4%,D:1.3%]). So, is it necessary to purge my assembly genome? or maybe purge_dups made my assembly genome overpurged or worse?

**Comment by StevenBai97** [comment]
@lh3

**Comment by chhylp123** [comment]
How do you run purge_dups? Did you run it on both p_ctg and a_ctg? I guess from BUSCO scores, it is OK. Short reads maybe not such important. In addition, we have already fixed the insufficient purging issue of hifiasm. If you think it is important, I can  push it to github repo right now.

**Comment by StevenBai97** [comment]
I didn't run purge_dups on both p_ctg and a_ctg. I think the quality of a_ctg is not high (N50 ~ 400Kb) and the size of a_ctg is about 500Mb, so I only used p_ctg to purge. I quite looked forward to the improved version of hifiasm, because I believe that new version will clear my confusion about purging. Please release it as soon as possible. 
Thanks for your hifiasm and suggestions. 
@chhylp123

**Comment by chhylp123** [comment]
@StevenBai97  Please have a try using the option '-l3' with github HEAD (0.14-r313). '-s' is able to further adjust the results. Note that the option '--high-het' is removed for now, since ordinary bin files without '--high-het' + '-l3' already works on my sides. If you have bin files generated by '--high-het', '-l3' may also work. Hope '-l3' can fix the purging problems for your sample.

**Comment by StevenBai97** [comment]
Thanks for your improvement and suggestions. I have uesd the option '-l3' with github HEAD (0.14-r313) and get a great assembly genome (N50: 5.1Mb, BUSCO: 98.7%[S:97.7%,D:1.0%]). I believe this is the best result for my sample, and will use AllHiC to cluster and anchor these contigs.

**Comment by chhylp123** [comment]
Great! Looking forward to your results.
